### PR TITLE
Updated the feature set of p3270

### PR DESCRIPTION
**Pull request by simonfaltum**
I needed a 3270-emulator in python for a project, and found this one to be the best one but with some features I needed lacking.
I have added some features and made a few things a bit more dynamic + added option for selecting encoding.

I have tested it pretty well.

### CODE REVIEW

**Comment by simonfaltum** [comment]
Is this repo abandoned / not being maintained anymore?

**Comment by mstiri** [comment]
> Is this repo abandoned / not being maintained anymore?

Thank you @simonfaltum for the pull request. I will have a look at the commits and merge it.

**Comment by simonfaltum** [comment]
> > Is this repo abandoned / not being maintained anymore?
> 
> Thank you @simonfaltum for the pull request. I will have a look at the commits and merge it.

Thanks :) I wouldn't mind to increase the automated tests but you would have to help me a bit to get started as I have zero experience with it in python

**Comment by mstiri** [comment]
> > > Is this repo abandoned / not being maintained anymore?
> > 
> > 
> > Thank you @simonfaltum for the pull request. I will have a look at the commits and merge it.
> 
> Thanks :) I wouldn't mind to increase the automated tests but you would have to help me a bit to get started as I have zero experience with it in python


Of course, it would be great if we can increase the test coverage. 
Thank you. The merge request is merged into master and tagged (v0.1.3). A new release has been also uploaded to the pypi repository so it can be installed directly using `pip` command. 
Thank you very much for your contribution.

**Pull request merged**
